### ISSUE TITLE
[BE] rework app parameters approach from ENVs to single config.yaml

### ISSUE THREAD

**Issue by alagishev** [Netcracker/qubership-apihub#208]
*The idea*:

For now all apihub-backend parameters (technical and business, both) are provided by ENV variables. It is fine but set of all ENVs is pretty huge already and keep growing. At the same time all these parameter can be grouped by sense. So plain list of ENVs is a hard to manage and document.
YAML structured parameters looks simpler, more human-understandable, scalable and golang code working with config.yaml files looks more straightforward.

*Design:*

1. Remove all ENV VARs (exceptions: GIT_HASH, GIT_BRANCH which are set in docker image during build process)
2. Introduce single ENV VAR: `APIHUB_YAML_CONFIG_FILE_PATH` which contains folder with `config.yaml` file with all parameters in it. If not set - defaults to `./` folder (run from IDE or on local machine case).
3. In k8s `config.yaml` file mounted from secret. See implementation here: TODO
4. `viper` golang library seems to be good choice for working with config.yaml

*config.yaml design:*

Initial proposal (to be reviewed and discussed):

Based on Helm chart `values.yaml` (see https://github.com/Netcracker/qubership-apihub/blob/main/helm-templates/qubership-apihub/values.yaml)

```
# Section with global APIHUB configuration
qubershipApihub:
  # Optional; APIHUB release version to be shown in UI; If not set, default value: unknown; Example: 37653
  version: 'yaml-params'
  # Optional; Set log level on init to specified value. Values: Info, Warn, Error, etc; If not set, default value: INFO; Example: DEBUG
  logLevel: 'INFO'
  # Mandatory; Default system access token (any string). The token will be provisioned automatically during startup; If not set, default value: ""; Example: access-token-12345
  accessToken: 'xyz'
  # Mandatory; Factual APIHUB server URL in your environment.; If not set, default value: ""; Example: https://apihub.example.com
  apihubUrl: 'https://apihub.example.com'

  backend:
    # Optional; Enables production mode - login under local apihub users is prohibited in this mode. In this mode only SAML auth is possible, so SAML integration related deploy parameters are mandatory in this case; If not set, default value: FALSE; Example: TRUE
    productionMode: 'true'  # set to false at your own risk

    # Section with PostgreSQL database connection parameters
    database:
      # Mandatory; PostgreSQL database host ; If not set, default value: localhost; Example: postgres.example.com
      dbHost: 'pg.postgres.svc.local'
      # Mandatory; PostgreSQL database port; If not set, default value: 5432; Example: 5432
      dbPort: '5432'
      # Mandatory; Logical database in PostgreSQL cluster for APIHUB. Manual pre-creation required; If not set, default value: apihub; Example: apihub_backend_prod_db
      dbName: ''
      # Mandatory; User for APIHUB_POSTGRESQL_DB_NAME database; If not set, default value: apihub; Example: apihub_backend_prod_admin
      dbUsername: ''
      # Mandatory; Password for APIHUB_POSTGRESQL_USERNAME user.; If not set, default value: apihub; Example: apihub_backend_prod_password
      dbPassword: ''

    # Mandatory; Self generated private PKCS#8 private key, base64 encoded. Used for siging of JWT tokens issued by APIHUB, must be unique fore each APIHUB instance; If not set, default value: ""; Example: LS0tLS1CRUdJTiBQUklWQV...
    jwtPrivateKey: 'xyz'
    # Optional; Default local admin user login. If set - this admin user will be created automatically.; If not set, default value: ""; Example: admin@example.com
    adminEmail: ''
    # Optional; Default local admin user password; If not set, default value: ""; Example: admin-password
    adminPassword: ''

    # Section with SAML integration parameters. SAML integration is used for authentication and authorization of APIHUB users. SAML integration is mandatory for production mode.
    samlIntegration:
      # Optional; SAML metadata URL. If set - enables SAML integration; If not set, default value: ""; Example: https://idp.example.com/FederationMetadata/2007-06/FederationMetadata.xml
      adfsMetadataUrl: ''
      # Optional; SAML server certificate, base64 encoded. Required only if SAML integration enabled; If not set, default value: ""; Example: LS0tLS1CRUdJTi...
      crt: ''
      # Optional; SAML server private key, base64 encoded. Required only if SAML integration enabled; If not set, default value: ""; Example: LS0tLS1CRUdJTi...
      key: ''

    auth:
      - type: 'OIDC'
        url: 'https://oidc.example.com/authorize'
      - type: 'SAML'
        url: 'https://saml.example.com/authorize'

    # Section with various parameters related to APIHUB business logic
    businessParameters:
      # Optional; Links to be shown under (i) button in UI; If not set, default value: ""; Example: 
      externalLinks: ''
      # Optional; Default workspace ID for Agent UI; If not set, default value: ""; Example: QS
      defaultWorkspaceId: ''
      # Optional; Regex pattern for releases names validation.; If not set, default value: ^[0-9]{4}[.]{1}[1-4]{1}$; Example: ^2023\.1$
      releaseVersionPattern: '.*'
      # Optional; Limit for uploaded package size in order to avoid OOM; If not set, default value: 50; Example: 50
      publishArchiveSizeLimitMb: '50'
      # Optional; Limit for uploaded file (inside package) size in order to avoid OOM; If not set, default value: 15; Example: 20
      publishFileSizeLimitMb: '15'
      # Optional; If set - footer with this text is shown for all APIHUB users in APIHUB UI. Designed for maintenance windows notifications.; If not set, default value: ""; Example: Maintenance scheduled on 2023-10-15
      systemNotification: ''
      # Optional; Set to true to enable apihub playground work without authtorization. Dangerous. Not recommended; If not set, default value: FALSE; Example: FALSE
      insecureProxy: 'FALSE'
      # Optional; Allowed list of hosts that are accepted for proxy(playground) requests.; If not set, default value: ""; Example: *.example.com
      allowedHosts: ''

    # Section with various parameters related to APIHUB technical behavior 
    technicalParameters:
      # Optional; Allows to set extra allowed origin to CORS header. Used for FE debugging. Should be empty on prod evs.; If not set, default value: ""; Example: https://localhost:5137
      originAllowed: '*'
      # Optional; Allows to specify custom paths for extension (plug-in) backend services; If not set, default value: ""; Example: 
      customPathPrefixes: ''

    # Section with LDAP integration parameters. LDAP integration is used for User syncronization. Makes sense only if SAML integration enabled.
    ldap:
      # Optional; LDAP server URL. Required for SAML integration for syncing users information; If not set, default value: ""; Example: ldap://ldap.example.com:389
      server: ''
      # Optional; LDAP User used for connecting to LDAP server; If not set, default value: ""; Example: x_apihub
      user: ''
      # Optional; Password for LDAP User; If not set, default value: ""; Example: x_apihub_password
      password: ''
      # Optional; Base DN to search users in; If not set, default value: ""; Example: organization
      baseDN: ''
      # Optional; Organization unit to search users in; If not set, default value: ""; Example: example
      organizationUnit: ''
      # Optional; Search base to search users in; If not set, default value: ""; Example: com
      searchBase: ''

    # Section with S3 storage integration parameters.
    storageServer:
      # Optional; Set to true to enable S3 integration. S3 is used for store temporary relatively large files.; If not set, default value: FALSE; Example: TRUE
      active: 'FALSE'
      # Optional; S3 endpoint for client connection; If not set, default value: ""; Example: s3.example.com
      url: ''
      # Optional; Access Key ID from S3 storage; If not set, default value: ""; Example: s3-access-key
      username: ''
      # Optional; Secret key for S3 storage access; If not set, default value: ""; Example: s3-secret-key
      password: ''
      # Optional; Certificate for accessing S3 storage; If not set, default value: ""; Example: LS0tLS1CRUdJTiBQUklWQV...
      crt: ''
      # Optional; Bucket name in S3 storage; If not set, default value: ""; Example: apihub-bucket
      bucketTame: ''
      # Optional; Set to true to store only build results (less data amout) in S3 storage; If not set, default value: FALSE; Example: TRUE
      storeOnlyBuildResult: ''

    # Parameters for APIHUB Editor feature. Deprecated. Will be removed in future releases.
    editor:
      gitlabUrl: ''
      clientId: ''
      clientSecret: ''
```

*Notes:*

1. Helm chart and docker-compose files must be modified as well
2. It is backward incompatible change, so single time deployment configuration on customer side would be required
