### ISSUE TITLE
[FE] Doc view doesn't reflect removed custom property

### ISSUE THREAD

**Issue by Maryna-Ko** [Netcracker/qubership-apihub#72]
### Describe the bug

Compare two versions

### To Reproduce

1. Publish two documents (version 1 and version 2)
2. Navigate to API changes to check highlighted discrepancies on both views (RAW and Doc)

version 1
```yaml
paths:
  /operation_path2:
    post:
      summary: Operation with cycles. test
      x-ext-domain: domain1
      description: This operation contains four types of cycles
```
version 2
```yaml
paths:
  /operation_path2:
    post:
      summary: Operation with cycles
      description: This operation contains four types of cycles
```

ER: removed custom property is highlighted in a proper way on both RAW and Doc views
AR: removed custom property is highlighted in RAW view ONLY (see attached screen)

![Image](https://github.com/user-attachments/assets/aee071f9-e192-40a5-9517-1e7bf274387d)

### Version

38 (Drop 2)
